table DimCompany
	lineageTag: d6c6dce4-d930-4167-b5cd-5e906bd552ec

	measure 'Company Count' =
			
			DISTINCTCOUNT(FactVehicle[Company])
		formatString: 0
		displayFolder: _CORE
		lineageTag: 4a821ea8-6668-4e0b-baf3-7bbca8534167

	column Company_ID
		dataType: int64
		formatString: 0
		lineageTag: 5aab3e63-7bd1-4266-bd14-4c2909cf30a8
		summarizeBy: none
		sourceColumn: Company_ID

		annotation SummarizationSetBy = Automatic

	column Company
		dataType: string
		lineageTag: 7e663693-2e55-487a-86d9-e08bfa7bdf6b
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	partition DimCompany = m
		mode: import
		queryGroup: 'Main Querys'
		source = ```
				let
				  Source = Csv.Document(File.Contents("C:\Users\Juanma\Desktop\cars-intelligence-2025\data\raw\Cars Datasets 2025.csv"), [Delimiter = ",", Columns = 11, QuoteStyle = QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Company Names", type text}, {"Cars Names", type text}, {"Engines", type text}, {"CC/Battery Capacity", type text}, {"HorsePower", type text}, {"Total Speed", type text}, {"Performance(0 - 100 )KM/H", type text}, {"Cars Prices", type text}, {"Fuel Types", type text}, {"Seats", type text}, {"Torque", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Company Names", "Company"}, {"Cars Names", "Car_Name"}, {"Engines", "Engine_Raw"}, {"CC/Battery Capacity", "CC_Battery_Raw"}, {"HorsePower", "HorsePower_Raw"}, {"Total Speed", "Speed_Raw"}, {"Performance(0 - 100 )KM/H", "Acceleration_Raw"}, {"Cars Prices", "Price_Raw"}, {"Fuel Types", "Fuel_Raw"}, {"Seats", "Seats_Raw"}, {"Torque", "Torque_Raw"}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Renamed Columns",{{"Company", Text.Trim, type text}, {"Car_Name", Text.Trim, type text}, {"Engine_Raw", Text.Trim, type text}, {"CC_Battery_Raw", Text.Trim, type text}, {"HorsePower_Raw", Text.Trim, type text}, {"Speed_Raw", Text.Trim, type text}, {"Acceleration_Raw", Text.Trim, type text}, {"Price_Raw", Text.Trim, type text}, {"Fuel_Raw", Text.Trim, type text}, {"Seats_Raw", Text.Trim, type text}, {"Torque_Raw", Text.Trim, type text}}),
				    #"Cleaned Text" = Table.TransformColumns(#"Trimmed Text",{{"Company", Text.Clean, type text}, {"Car_Name", Text.Clean, type text}, {"Engine_Raw", Text.Clean, type text}, {"CC_Battery_Raw", Text.Clean, type text}, {"HorsePower_Raw", Text.Clean, type text}, {"Speed_Raw", Text.Clean, type text}, {"Acceleration_Raw", Text.Clean, type text}, {"Price_Raw", Text.Clean, type text}, {"Fuel_Raw", Text.Clean, type text}, {"Seats_Raw", Text.Clean, type text}, {"Torque_Raw", Text.Clean, type text}}),
				    #"Added Custom" = Table.AddColumn(#"Cleaned Text", "HorsePower_Avg", each fx_ParseRangeNumber([HorsePower_Raw])),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"HorsePower_Avg", type number}}),
				    #"Added Custom1" = Table.AddColumn(#"Changed Type1", "Speed_KMH", each try Number.FromText(
				    Text.BeforeDelimiter(
				        Text.Lower([Speed_Raw]),
				        "km/h"
				    )
				) otherwise null),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom1",{{"Speed_KMH", type number}}),
				    #"Added Custom2" = Table.AddColumn(#"Changed Type2", "Acceleration_0_100_Sec", each try Number.FromText(
				    Text.Trim(
				        Text.Replace(
				            Text.BeforeDelimiter(
				                Text.Lower([Acceleration_Raw]),
				                "sec"
				            ),
				            " ",
				            ""
				         )
				    )
				) otherwise null),
				    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "Price_Min_USD", each let
				    Raw = if [Price_Raw] = null then null else Text.Trim([Price_Raw]),
				    Clean = if Raw = null then null
				            else Text.Replace(
				                    Text.Replace(Raw, "$", ""),
				                    ",",
				                    ""
				                 ),
				    Parts = if Clean = null then {}
				            else List.Transform(
				                    Text.Split(Clean, "-"),
				                    each Text.Trim(_)
				                 ),
				    Numbers =
				        List.RemoveNulls(
				            List.Transform(
				                Parts,
				                each
				                    try Number.FromText(_, "en-US")
				                    otherwise null
				            )
				        )
				in
				    if List.Count(Numbers) = 0
				    then null
				    else List.Min(Numbers)),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom3",{{"Price_Min_USD", type number}}),
				    #"Added Custom4" = Table.AddColumn(#"Changed Type3", "Price_Max_USD", each let
				    Raw = if [Price_Raw] = null then null else Text.Trim([Price_Raw]),
				    Clean = if Raw = null then null
				            else Text.Replace(
				                    Text.Replace(Raw, "$", ""),
				                    ",",
				                    ""
				                 ),
				    Parts = if Clean = null then {}
				            else List.Transform(
				                    Text.Split(Clean, "-"),
				                    each Text.Trim(_)
				                 ),
				    Numbers =
				        List.RemoveNulls(
				            List.Transform(
				                Parts,
				                each
				                    try Number.FromText(_, "en-US")
				                    otherwise null
				            )
				        )
				in
				    if List.Count(Numbers) = 0
				    then null
				    else List.Max(Numbers)),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Added Custom4",{{"Price_Max_USD", type number}}),
				    #"Added Custom5" = Table.AddColumn(#"Changed Type4", "Price_Avg_USD", each let
				    Raw = if [Price_Raw] = null then null else Text.Trim([Price_Raw]),
				    Clean = if Raw = null then null
				            else Text.Replace(
				                    Text.Replace(Raw, "$", ""),
				                    ",",
				                    ""
				                 ),
				    Parts = if Clean = null then {}
				            else List.Transform(
				                    Text.Split(Clean, "-"),
				                    each Text.Trim(_)
				                 ),
				    Numbers =
				        List.RemoveNulls(
				            List.Transform(
				                Parts,
				                each
				                    try Number.FromText(_, "en-US")
				                    otherwise null
				            )
				        )
				in
				    if List.Count(Numbers) = 0
				    then null
				    else List.Average(Numbers)),
				    #"Added Custom6" = Table.AddColumn(#"Added Custom5", "Price_Is_Range", each if [Price_Min_USD] <> [Price_Max_USD]
				then true 
				else false),
				    #"Changed Type5" = Table.TransformColumnTypes(#"Added Custom6",{{"Price_Is_Range", type logical}}),
				    #"Added Custom7" = Table.AddColumn(#"Changed Type5", "Torque_Min_Nm", each let
				    Raw = if [Torque_Raw] = null then null else Text.Lower(Text.Trim([Torque_Raw])),
				    Clean = if Raw = null then null
				            else Text.Replace(
				                    Text.Replace(Raw, "nm", ""),
				                    ",",
				                    ""
				                 ),
				    Parts = if Clean = null then {}
				            else List.Transform(Text.Split(Clean, "-"), each Text.Trim(_)),
				    Numbers =
				        List.RemoveNulls(
				            List.Transform(
				                Parts,
				                each
				                    try Number.FromText(_, "en-US")
				                    otherwise null
				            )
				        )
				in
				    if List.Count(Numbers) = 0
				    then null
				    else List.Min(Numbers)),
				    #"Added Custom8" = Table.AddColumn(#"Added Custom7", "Torque_Max_Nm", each let
				    Raw = if [Torque_Raw] = null then null else Text.Lower(Text.Trim([Torque_Raw])),
				    Clean = if Raw = null then null
				            else Text.Replace(
				                    Text.Replace(Raw, "nm", ""),
				                    ",",
				                    ""
				                 ),
				    Parts = if Clean = null then {}
				            else List.Transform(Text.Split(Clean, "-"), each Text.Trim(_)),
				    Numbers =
				        List.RemoveNulls(
				            List.Transform(
				                Parts,
				                each
				                    try Number.FromText(_, "en-US")
				                    otherwise null
				            )
				        )
				in
				    if List.Count(Numbers) = 0
				    then null
				    else List.Max(Numbers)),
				    #"Added Custom9" = Table.AddColumn(#"Added Custom8", "Torque_Avg_Nm", each let
				    Raw = if [Torque_Raw] = null then null else Text.Lower(Text.Trim([Torque_Raw])),
				    Clean = if Raw = null then null
				            else Text.Replace(
				                    Text.Replace(Raw, "nm", ""),
				                    ",",
				                    ""
				                 ),
				    Parts = if Clean = null then {}
				            else List.Transform(Text.Split(Clean, "-"), each Text.Trim(_)),
				    Numbers =
				        List.RemoveNulls(
				            List.Transform(
				                Parts,
				                each
				                    try Number.FromText(_, "en-US")
				                    otherwise null
				            )
				        )
				in
				    if List.Count(Numbers) = 0
				    then null
				    else List.Average(Numbers)),
				    #"Changed Type6" = Table.TransformColumnTypes(#"Added Custom9",{{"Torque_Avg_Nm", type number}, {"Torque_Max_Nm", type number}, {"Torque_Min_Nm", type number}, {"Price_Avg_USD", type number}, {"Acceleration_0_100_Sec", type number}}),
				    #"Added Custom10" = Table.AddColumn(#"Changed Type6", "Seats_Count", each let
				    Raw =
				        if [Seats_Raw] = null
				        then null
				        else Text.Lower(Text.Trim([Seats_Raw])),
				
				    Parts =
				        if Raw = null
				        then {}
				        else Text.Split(Raw, "+"),
				
				    Numbers =
				        List.RemoveNulls(
				            List.Transform(
				                Parts,
				                each
				                    try Number.FromText(
				                        Text.Trim(_),
				                        "en-US"
				                    )
				                    otherwise null
				            )
				        )
				in
				    if List.Count(Numbers) = 0
				    then null
				    else List.Sum(Numbers)),
				    #"Changed Type7" = Table.TransformColumnTypes(#"Added Custom10",{{"Seats_Count", Int64.Type}}),
				    #"Added Custom11" = Table.AddColumn(#"Changed Type7", "Seats_Layout", each if [Seats_Raw] <> null 
				    and Text.Contains([Seats_Raw], "+")
				then Text.Trim([Seats_Raw])
				else null),
				    #"Added Custom12" = Table.AddColumn(#"Added Custom11", "Fuel_Group", each let
				    Fuel =
				        if [Fuel_Raw] = null 
				        then ""
				        else Text.Lower(Text.Trim([Fuel_Raw]))
				in 
				    if Fuel = "petrol" then "Petrol"
				    else if Fuel = "diesel" then "Diesel"
				    else if Fuel = "electric" then "Electric"
				    else if Fuel = "hybrid" then "Hybrid"
				    else if Text.Contains(Fuel, "plug")
				    and Text.Contains(Fuel,"hybrid") then "Plug-in Hybrid"
				    else if Text.Contains(Fuel, "petrol") and (Text.Contains(Fuel, "hybrid") or Text.Contains(Fuel, "diesel") or Text.Contains(Fuel, "ev")) then "Multi-Fuel"
				    else "Other"),
				    #"Added Custom13" = Table.AddColumn(#"Added Custom12", "Engine_Displacement_CC", each let
				    Raw =
				        if [CC_Battery_Raw] = null
				        then ""
				        else Text.Lower(Text.Trim([CC_Battery_Raw])),
				
				    Parts =
				        List.Transform(
				            Text.Split(Raw, "/"),
				            each Text.Trim(_)
				        ),
				
				    CCParts =
				        List.Select(
				            Parts,
				            each Text.Contains(_, "cc")
				        ),
				
				    FirstCC =
				        if List.Count(CCParts) > 0
				        then CCParts{0}
				        else null,
				
				    NumberText =
				        if FirstCC = null
				        then null
				        else Text.BeforeDelimiter(
				            FirstCC,
				            "cc"
				        ),
				
				    CleanNumber =
				        if NumberText = null
				        then null
				        else Text.Replace(
				            Text.Replace(
				                Text.Trim(NumberText),
				                ",",
				                ""
				            ),
				            " ",
				            ""
				        )
				in
				    try Number.FromText(
				        CleanNumber,
				        "en-US"
				    )
				    otherwise null),
				    #"Added Custom14" = Table.AddColumn(#"Added Custom13", "Battery_Capacity_KWh", each let
				    Raw =
				        if [CC_Battery_Raw] = null
				        then ""
				        else Text.Lower(Text.Trim([CC_Battery_Raw])),
				
				    Parts =
				        List.Transform(
				            Text.Split(Raw, "/"),
				            each Text.Trim(_)
				        ),
				
				    KWhParts =
				        List.Select(
				            Parts,
				            each Text.Contains(_, "kwh")
				        ),
				
				    FirstKWh =
				        if List.Count(KWhParts) > 0
				        then KWhParts{0}
				        else null,
				
				    NumberText =
				        if FirstKWh = null
				        then null
				        else Text.BeforeDelimiter(
				            FirstKWh,
				            "kwh"
				        ),
				
				    CleanNumber =
				        if NumberText = null
				        then null
				        else Text.Replace(
				            Text.Trim(NumberText),
				            " ",
				            ""
				        )
				in
				    try Number.FromText(
				        CleanNumber,
				        "en-US"
				    )
				    otherwise null),
				    #"Added Custom15" = Table.AddColumn(#"Added Custom14", "DataQuality_Flag", each let
				    Issues =
				        List.RemoveNulls({
				            if [Company] = null or Text.Trim([Company]) = ""
				                then "COMPANY"
				                else null,
				
				            if [Car_Name] = null or Text.Trim([Car_Name]) = ""
				                then "CAR_NAME"
				                else null,
				
				            if [Price_Avg_USD] = null
				                then "PRICE"
				                else null,
				
				            if [HorsePower_Avg] = null
				                then "HP"
				                else null,
				
				            if [Speed_KMH] = null
				                then "SPEED"
				                else null,
				
				            if [Acceleration_0_100_Sec] = null
				                then "ACCELERATION"
				                else null,
				
				            if [Torque_Avg_Nm] = null
				                then "TORQUE"
				                else null,
				
				            if [Seats_Count] = null
				                then "SEATS"
				                else null,
				
				            if [Fuel_Group] = "Other"
				                then "FUEL_REVIEW"
				                else null
				        })
				in
				    if List.Count(Issues) = 0
				    then "OK"
				    else Text.Combine(
				        Issues,
				        "; "
				    )),
				    #"Added Custom16" = Table.AddColumn(#"Added Custom15", "Quality_Issue_Count", each let
				    Issues =
				        List.RemoveNulls({
				            if [Company] = null or Text.Trim([Company]) = ""
				                then 1 else null,
				
				            if [Car_Name] = null or Text.Trim([Car_Name]) = ""
				                then 1 else null,
				
				            if [Price_Avg_USD] = null
				                then 1 else null,
				
				            if [HorsePower_Avg] = null
				                then 1 else null,
				
				            if [Speed_KMH] = null
				                then 1 else null,
				
				            if [Acceleration_0_100_Sec] = null
				                then 1 else null,
				
				            if [Torque_Avg_Nm] = null
				                then 1 else null,
				
				            if [Seats_Count] = null
				                then 1 else null,
				
				            if [Fuel_Group] = "Other"
				                then 1 else null
				        })
				in
				    List.Count(Issues)),
				    #"Added Custom17" = Table.AddColumn(#"Added Custom16", "Vehicle_ID", each Text.Combine(
				    {
				        Text.Trim([Company]),
				        Text.Trim([Car_Name]),
				        Text.Trim([Engine_Raw])
				    },
				    "|"
				)),
				    #"Added Custom18" = Table.AddColumn(#"Added Custom17", "HorsePower_Min", each let
				    Raw =
				        if [HorsePower_Raw] = null
				        then null
				        else Text.Lower(Text.Trim([HorsePower_Raw])),
				
				    Clean =
				        if Raw = null
				        then null
				        else Text.Replace(
				            Text.Replace(Raw, "hp", ""),
				            ",",
				            ""
				        ),
				
				    Parts =
				        if Clean = null
				        then {}
				        else List.Transform(
				            Text.Split(Clean, "-"),
				            each Text.Trim(_)
				        ),
				
				    Numbers =
				        List.RemoveNulls(
				            List.Transform(
				                Parts,
				                each
				                    try Number.FromText(_, "en-US")
				                    otherwise null
				            )
				        )
				in
				    if List.Count(Numbers) = 0
				    then null
				    else List.Min(Numbers)),
				    #"Added Custom19" = Table.AddColumn(#"Added Custom18", "HorsePower_Max", each let
				    Raw =
				        if [HorsePower_Raw] = null
				        then null
				        else Text.Lower(Text.Trim([HorsePower_Raw])),
				
				    Clean =
				        if Raw = null
				        then null
				        else Text.Replace(
				            Text.Replace(Raw, "hp", ""),
				            ",",
				            ""
				        ),
				
				    Parts =
				        if Clean = null
				        then {}
				        else List.Transform(
				            Text.Split(Clean, "-"),
				            each Text.Trim(_)
				        ),
				
				    Numbers =
				        List.RemoveNulls(
				            List.Transform(
				                Parts,
				                each
				                    try Number.FromText(_, "en-US")
				                    otherwise null
				            )
				        )
				in
				    if List.Count(Numbers) = 0
				    then null
				    else List.Max(Numbers)),
				    #"Added Custom20" = Table.AddColumn(#"Added Custom19", "HP_Is_Range", each [HorsePower_Min] <> [HorsePower_Max]),
				    #"Changed Type8" = Table.TransformColumnTypes(#"Added Custom20",{{"HP_Is_Range", type logical}, {"HorsePower_Max", type number}, {"HorsePower_Min", type number}, {"Quality_Issue_Count", Int64.Type}, {"Engine_Displacement_CC", type number}, {"Battery_Capacity_KWh", type number}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Changed Type8",{"Vehicle_ID", "Company", "Car_Name", "Engine_Raw", "CC_Battery_Raw", "Engine_Displacement_CC", "Battery_Capacity_KWh", "HorsePower_Raw", "Speed_Raw", "Acceleration_Raw", "Price_Raw", "HorsePower_Min", "HorsePower_Max", "HorsePower_Avg", "Speed_KMH", "Acceleration_0_100_Sec", "Price_Min_USD", "Price_Max_USD", "Price_Avg_USD", "Price_Is_Range", "Fuel_Raw", "Fuel_Group", "Seats_Raw", "Seats_Count", "Seats_Layout", "Torque_Raw", "Torque_Min_Nm", "Torque_Max_Nm", "Torque_Avg_Nm", "DataQuality_Flag", "Quality_Issue_Count", "HP_Is_Range"}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Reordered Columns",{"Company"}),
				    #"Uppercased Text" = Table.TransformColumns(#"Removed Other Columns",{{"Company", Text.Upper, type text}}),
				    #"Removed Duplicates" = Table.Distinct(#"Uppercased Text"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Index",{{"Index", "Company_ID"}}),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Renamed Columns1",{"Company_ID", "Company"})
				in
				    #"Reordered Columns1"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

