table DimCompany
	lineageTag: d6c6dce4-d930-4167-b5cd-5e906bd552ec

	column Company
		dataType: string
		lineageTag: 7e663693-2e55-487a-86d9-e08bfa7bdf6b
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	column Company_ID
		dataType: int64
		formatString: 0
		lineageTag: 9ce637f3-7370-4f3c-8d19-e8559d3cc8b3
		summarizeBy: none
		sourceColumn: Company_ID

		annotation SummarizationSetBy = Automatic

	partition DimCompany = m
		mode: import
		queryGroup: 'Main Querys'
		source =
				let
				    Source = stg_Cars_Raw,
				    #"Selected Columns" = Table.SelectColumns(Source, {"Company"}),
				    #"Removed Duplicates" = Table.Distinct(#"Selected Columns"),
				    #"Added Index" = Table.AddIndexColumn(#"Removed Duplicates", "Company_ID", 1, 1, Int64.Type),
				    #"Reordered Columns" = Table.ReorderColumns(#"Added Index", {"Company_ID", "Company"})
				in
				    #"Reordered Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

