table DimEngine
	lineageTag: 866604e2-bb92-4ecd-92fb-0a0dd2f5df3c

	column Engine_Raw
		dataType: string
		lineageTag: 3b63030a-606e-490f-bbc8-d194bb7b5b7a
		summarizeBy: none
		sourceColumn: Engine_Raw

		annotation SummarizationSetBy = Automatic

	column Engine_Key
		dataType: string
		lineageTag: d606f294-d04e-43db-adbd-fb8a1c1864f2
		summarizeBy: none
		sourceColumn: Engine_Key

		annotation SummarizationSetBy = Automatic

	partition DimEngine = m
		mode: import
		queryGroup: 'Main Querys'
		source =
				let
				    Source = stg_Cars_Raw,
				    #"Selected Columns" = Table.SelectColumns(Source, {"Engine_Raw", "Engine_Key"}),
				    #"Removed Duplicates" = Table.Distinct(#"Selected Columns", {"Engine_Key"})
				in
				    #"Removed Duplicates"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

