table FactVehicle
	lineageTag: efbb30da-6fcb-4c55-a447-465d482075fc

	measure 'Vehicle Rows' =
			
			COUNTROWS(FactVehicle)
		formatString: 0
		lineageTag: 07767128-b2b8-4351-8218-7e3420c82aef

	measure 'Vehicle Count' =
			
			DISTINCTCOUNT(FactVehicle[Vehicle_ID])
		formatString: 0
		displayFolder: _CORE
		lineageTag: 07f702f1-7c4c-4b96-8756-45dad203df87

	measure 'Distinct NaturalKey' =
			
			DISTINCTCOUNT(FactVehicle[Vehicle_NaturalKey])
		formatString: 0
		lineageTag: 849b4900-793f-49a9-8258-1a0d63ae4131

	measure 'Median Price' =
			
			MEDIAN(FactVehicle[Price_Avg_USD])
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _PRICE
		lineageTag: 2f037880-8ec8-481a-8e9c-b9f7dda9097e

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Average Price' =
			
			AVERAGE(FactVehicle[Price_Avg_USD])
		formatString: \$#,0;(\$#,0);\$#,0
		displayFolder: _PRICE
		lineageTag: c8882442-b03c-463c-9d3d-85b045cb3b6c

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	measure 'Min Price' =
			
			MIN (FactVehicle[Price_Avg_USD])
		displayFolder: _PRICE
		lineageTag: e6c85d71-c4c3-4cb3-934c-7bb97353aefa

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Max Price' =
			
			MAX (FactVehicle[Price_Avg_USD])
		displayFolder: _PRICE
		lineageTag: d343ee8b-9955-496a-a26f-80f66af00a2b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average HP' =
			
			AVERAGE (FactVehicle[HorsePower_Avg])
		displayFolder: _PERFORMANCE
		lineageTag: cf8cc606-d617-4ca6-b07d-ad4fe3421f33

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Median HP' =
			
			MEDIAN(FactVehicle[HorsePower_Avg])
		displayFolder: _PERFORMANCE
		lineageTag: 1e7e3c82-6133-4388-9c23-677c01d6bc3b

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Min HP' =
			
			MIN(FactVehicle[HorsePower_Avg])
		displayFolder: _PERFORMANCE
		lineageTag: c4b150d0-b40a-4041-bce3-662677fab4eb

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Max HP' =
			
			MAX(FactVehicle[HorsePower_Avg])
		displayFolder: _PERFORMANCE
		lineageTag: 5ae76bb2-2aa4-415f-bb17-f367c9a77406

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Speed' =
			
			AVERAGE(FactVehicle[Speed_KMH])
		displayFolder: _PERFORMANCE
		lineageTag: 757b3179-0470-4da1-96dd-ebe2cca754d0

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Median Speed' =
			
			MEDIAN(FactVehicle[Speed_KMH])
		displayFolder: _PERFORMANCE
		lineageTag: ffc1f1d8-74da-41dd-b1ae-ce3ad1d23da3

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Min Speed' =
			
			MIN(FactVehicle[Speed_KMH])
		displayFolder: _PERFORMANCE
		lineageTag: 31a50a77-11cd-4751-b1d4-84f1215ada2c

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Max Speed' =
			
			MAX(FactVehicle[Speed_KMH])
		displayFolder: _PERFORMANCE
		lineageTag: 1b2188ba-1add-4e24-824f-260d2127c268

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average 0-100' =
			
			AVERAGE(FactVehicle[Acceleration_0_100_Sec])
		displayFolder: _PERFORMANCE
		lineageTag: 0a283bed-7801-4773-97af-53e25d765065

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Median 0-100' =
			
			MEDIAN(FactVehicle[Acceleration_0_100_Sec])
		displayFolder: _PERFORMANCE
		lineageTag: 26d12192-ba4a-40d4-89ca-c6cdabc62a30

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Min 0-100' =
			
			MIN(FactVehicle[Acceleration_0_100_Sec])
		displayFolder: _PERFORMANCE
		lineageTag: 00a20a08-e5de-49ee-880a-16769680e58d

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Average Torque' =
			
			AVERAGE ( FactVehicle[Torque_Avg_Nm] )
		displayFolder: _PERFORMANCE
		lineageTag: 548da329-bc4c-4f09-8f80-d7c9f1bf1ef8

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Median Torque' =
			
			MEDIAN ( FactVehicle[Torque_Avg_Nm] )
		displayFolder: _PERFORMANCE
		lineageTag: 8972af6d-f7de-4060-8e9e-35a9f4db1f73

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Min Torque' =
			
			MIN ( FactVehicle[Torque_Avg_Nm] )
		displayFolder: _PERFORMANCE
		lineageTag: 8e66b2ef-7cfe-45f5-b401-eaa41cad5aa1

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	measure 'Max Torque' =
			
			MAX ( FactVehicle[Torque_Avg_Nm] )
		displayFolder: _PERFORMANCE
		lineageTag: fc7725f9-f91c-4a47-9d2f-209de2e22364

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Vehicle_NaturalKey
		dataType: string
		lineageTag: 6aed4cc7-c4f5-4674-aebf-51f675ea169b
		summarizeBy: none
		sourceColumn: Vehicle_NaturalKey

		annotation SummarizationSetBy = Automatic

	column Company
		dataType: string
		lineageTag: 25ca5524-f548-4b75-b960-37f82e3fc090
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	column Car_Name
		dataType: string
		lineageTag: fa1e43f7-7220-4e42-9670-000c09ad8932
		summarizeBy: none
		sourceColumn: Car_Name

		annotation SummarizationSetBy = Automatic

	column Engine_Raw
		dataType: string
		lineageTag: c5333a50-b850-4a3a-ac64-434b3ea1ad79
		summarizeBy: none
		sourceColumn: Engine_Raw

		annotation SummarizationSetBy = Automatic

	column CC_Battery_Raw
		dataType: string
		lineageTag: ddb8b14f-302c-45ae-8524-ce20094a0bf4
		summarizeBy: none
		sourceColumn: CC_Battery_Raw

		annotation SummarizationSetBy = Automatic

	column Engine_Displacement_CC
		dataType: double
		lineageTag: dccf51b9-97d1-413c-9981-165ca1636983
		summarizeBy: sum
		sourceColumn: Engine_Displacement_CC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Battery_Capacity_KWh
		dataType: double
		lineageTag: 40cf2aa9-180f-4f93-9e4d-540dd70d1552
		summarizeBy: sum
		sourceColumn: Battery_Capacity_KWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HorsePower_Min
		dataType: double
		lineageTag: 24529417-8a52-468a-9aa7-644c4923ad13
		summarizeBy: sum
		sourceColumn: HorsePower_Min

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HorsePower_Max
		dataType: double
		lineageTag: 816a9634-2771-4fb9-a51a-63de4fdeb18a
		summarizeBy: sum
		sourceColumn: HorsePower_Max

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HorsePower_Avg
		dataType: double
		lineageTag: a8e58c96-ff8b-4fff-b5f3-1678b2c32c45
		summarizeBy: sum
		sourceColumn: HorsePower_Avg

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Speed_KMH
		dataType: double
		lineageTag: 4b4624d1-a27b-4533-9828-8d5ee43702a0
		summarizeBy: sum
		sourceColumn: Speed_KMH

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Acceleration_0_100_Sec
		dataType: double
		lineageTag: 43eb5cf3-4e77-44ab-b704-1f4fd858b863
		summarizeBy: sum
		sourceColumn: Acceleration_0_100_Sec

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Price_Min_USD
		dataType: double
		lineageTag: a16e661c-fae1-4f68-a147-51dc56d035e4
		summarizeBy: sum
		sourceColumn: Price_Min_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Price_Max_USD
		dataType: double
		lineageTag: 18b9a35d-8652-4cad-930e-920dd194771a
		summarizeBy: sum
		sourceColumn: Price_Max_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Price_Avg_USD
		dataType: double
		lineageTag: a08228c2-de78-450c-9a2c-ddc2d2cfbe14
		summarizeBy: sum
		sourceColumn: Price_Avg_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Price_Is_Range
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 92fedc0f-501c-4461-b3f4-998a5c37dbf5
		summarizeBy: none
		sourceColumn: Price_Is_Range

		annotation SummarizationSetBy = Automatic

	column Fuel_Raw
		dataType: string
		lineageTag: bd01b5c5-6d30-40a9-b818-d2436b7cbc6c
		summarizeBy: none
		sourceColumn: Fuel_Raw

		annotation SummarizationSetBy = Automatic

	column Fuel_Group
		dataType: string
		lineageTag: 43f087a1-437f-47c8-8a13-1eca61a4b279
		summarizeBy: none
		sourceColumn: Fuel_Group

		annotation SummarizationSetBy = Automatic

	column Seats_Raw
		dataType: string
		lineageTag: 1237e4c1-62ae-4f30-8892-d3ee5d1a9997
		summarizeBy: none
		sourceColumn: Seats_Raw

		annotation SummarizationSetBy = Automatic

	column Seats_Count
		dataType: int64
		formatString: 0
		lineageTag: 99274145-35c2-423b-ba52-4587d445e372
		summarizeBy: sum
		sourceColumn: Seats_Count

		annotation SummarizationSetBy = Automatic

	column Seats_Layout
		dataType: string
		lineageTag: b734989f-90b3-464c-ab37-28c21f2a868e
		summarizeBy: none
		sourceColumn: Seats_Layout

		annotation SummarizationSetBy = Automatic

	column Torque_Raw
		dataType: string
		lineageTag: 8c0468be-7288-4af9-8495-4492dae8494b
		summarizeBy: none
		sourceColumn: Torque_Raw

		annotation SummarizationSetBy = Automatic

	column Torque_Min_Nm
		dataType: double
		lineageTag: e43d3f9c-716a-415e-a97f-7e24a193e23a
		summarizeBy: sum
		sourceColumn: Torque_Min_Nm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Torque_Max_Nm
		dataType: double
		lineageTag: 243f844a-d447-49c0-a700-6fde5557c1f6
		summarizeBy: sum
		sourceColumn: Torque_Max_Nm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Torque_Avg_Nm
		dataType: double
		lineageTag: 585acedf-c33c-4997-917f-83fc2439d645
		summarizeBy: sum
		sourceColumn: Torque_Avg_Nm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DataQuality_Flag
		dataType: string
		lineageTag: 3595677f-f67a-4547-b299-a90c0ac6935f
		summarizeBy: none
		sourceColumn: DataQuality_Flag

		annotation SummarizationSetBy = Automatic

	column Quality_Issue_Count
		dataType: int64
		formatString: 0
		lineageTag: 9c5d117c-256c-4667-b136-5bf320cceb30
		summarizeBy: sum
		sourceColumn: Quality_Issue_Count

		annotation SummarizationSetBy = Automatic

	column Vehicle_ID
		dataType: int64
		formatString: 0
		lineageTag: 4480c2d2-2ab0-4a78-bb65-39e38154c25e
		summarizeBy: count
		sourceColumn: Vehicle_ID

		annotation SummarizationSetBy = Automatic

	column Engine_Key
		dataType: string
		lineageTag: a5ec1ee0-c666-47d5-bcac-c277214867dc
		summarizeBy: none
		sourceColumn: Engine_Key

		annotation SummarizationSetBy = Automatic

	partition FactVehicle = m
		mode: import
		queryGroup: 'Main Querys'
		source = ```
				let
				  Source = Csv.Document(File.Contents("C:\Users\Juanma\Desktop\cars-intelligence-2025\data\raw\Cars Datasets 2025.csv"), [Delimiter = ",", Columns = 11, QuoteStyle = QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Company Names", type text}, {"Cars Names", type text}, {"Engines", type text}, {"CC/Battery Capacity", type text}, {"HorsePower", type text}, {"Total Speed", type text}, {"Performance(0 - 100 )KM/H", type text}, {"Cars Prices", type text}, {"Fuel Types", type text}, {"Seats", type text}, {"Torque", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Company Names", "Company"}, {"Cars Names", "Car_Name"}, {"Engines", "Engine_Raw"}, {"CC/Battery Capacity", "CC_Battery_Raw"}, {"HorsePower", "HorsePower_Raw"}, {"Total Speed", "Speed_Raw"}, {"Performance(0 - 100 )KM/H", "Acceleration_Raw"}, {"Cars Prices", "Price_Raw"}, {"Fuel Types", "Fuel_Raw"}, {"Seats", "Seats_Raw"}, {"Torque", "Torque_Raw"}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Renamed Columns",{{"Company", Text.Trim, type text}, {"Car_Name", Text.Trim, type text}, {"Engine_Raw", Text.Trim, type text}, {"CC_Battery_Raw", Text.Trim, type text}, {"HorsePower_Raw", Text.Trim, type text}, {"Speed_Raw", Text.Trim, type text}, {"Acceleration_Raw", Text.Trim, type text}, {"Price_Raw", Text.Trim, type text}, {"Fuel_Raw", Text.Trim, type text}, {"Seats_Raw", Text.Trim, type text}, {"Torque_Raw", Text.Trim, type text}}),
				    #"Cleaned Text" = Table.TransformColumns(#"Trimmed Text",{{"Company", Text.Clean, type text}, {"Car_Name", Text.Clean, type text}, {"Engine_Raw", Text.Clean, type text}, {"CC_Battery_Raw", Text.Clean, type text}, {"HorsePower_Raw", Text.Clean, type text}, {"Speed_Raw", Text.Clean, type text}, {"Acceleration_Raw", Text.Clean, type text}, {"Price_Raw", Text.Clean, type text}, {"Fuel_Raw", Text.Clean, type text}, {"Seats_Raw", Text.Clean, type text}, {"Torque_Raw", Text.Clean, type text}}),
				    #"Added Custom" = Table.AddColumn(#"Cleaned Text", "HorsePower_Avg", each fx_ParseRangeNumber([HorsePower_Raw])),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"HorsePower_Avg", type number}}),
				    #"Added Custom1" = Table.AddColumn(#"Changed Type1", "Speed_KMH", each try Number.FromText(
				    Text.BeforeDelimiter(
				        Text.Lower([Speed_Raw]),
				        "km/h"
				    )
				) otherwise null),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom1",{{"Speed_KMH", type number}}),
				    #"Added Custom2" = Table.AddColumn(#"Changed Type2", "Acceleration_0_100_Sec", each try Number.FromText(
				    Text.Trim(
				        Text.Replace(
				            Text.BeforeDelimiter(
				                Text.Lower([Acceleration_Raw]),
				                "sec"
				            ),
				            " ",
				            ""
				         )
				    )
				) otherwise null),
				    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "Price_Min_USD", each let
				    Raw = if [Price_Raw] = null then null else Text.Trim([Price_Raw]),
				    Clean = if Raw = null then null
				            else Text.Replace(
				                    Text.Replace(Raw, "$", ""),
				                    ",",
				                    ""
				                 ),
				    Parts = if Clean = null then {}
				            else List.Transform(
				                    Text.Split(Clean, "-"),
				                    each Text.Trim(_)
				                 ),
				    Numbers =
				        List.RemoveNulls(
				            List.Transform(
				                Parts,
				                each
				                    try Number.FromText(_, "en-US")
				                    otherwise null
				            )
				        )
				in
				    if List.Count(Numbers) = 0
				    then null
				    else List.Min(Numbers)),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom3",{{"Price_Min_USD", type number}}),
				    #"Added Custom4" = Table.AddColumn(#"Changed Type3", "Price_Max_USD", each let
				    Raw = if [Price_Raw] = null then null else Text.Trim([Price_Raw]),
				    Clean = if Raw = null then null
				            else Text.Replace(
				                    Text.Replace(Raw, "$", ""),
				                    ",",
				                    ""
				                 ),
				    Parts = if Clean = null then {}
				            else List.Transform(
				                    Text.Split(Clean, "-"),
				                    each Text.Trim(_)
				                 ),
				    Numbers =
				        List.RemoveNulls(
				            List.Transform(
				                Parts,
				                each
				                    try Number.FromText(_, "en-US")
				                    otherwise null
				            )
				        )
				in
				    if List.Count(Numbers) = 0
				    then null
				    else List.Max(Numbers)),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Added Custom4",{{"Price_Max_USD", type number}}),
				    #"Added Custom5" = Table.AddColumn(#"Changed Type4", "Price_Avg_USD", each let
				    Raw = if [Price_Raw] = null then null else Text.Trim([Price_Raw]),
				    Clean = if Raw = null then null
				            else Text.Replace(
				                    Text.Replace(Raw, "$", ""),
				                    ",",
				                    ""
				                 ),
				    Parts = if Clean = null then {}
				            else List.Transform(
				                    Text.Split(Clean, "-"),
				                    each Text.Trim(_)
				                 ),
				    Numbers =
				        List.RemoveNulls(
				            List.Transform(
				                Parts,
				                each
				                    try Number.FromText(_, "en-US")
				                    otherwise null
				            )
				        )
				in
				    if List.Count(Numbers) = 0
				    then null
				    else List.Average(Numbers)),
				    #"Added Custom6" = Table.AddColumn(#"Added Custom5", "Price_Is_Range", each if [Price_Min_USD] <> [Price_Max_USD]
				then true 
				else false),
				    #"Changed Type5" = Table.TransformColumnTypes(#"Added Custom6",{{"Price_Is_Range", type logical}}),
				    #"Added Custom7" = Table.AddColumn(#"Changed Type5", "Torque_Min_Nm", each let
				    Raw = if [Torque_Raw] = null then null else Text.Lower(Text.Trim([Torque_Raw])),
				    Clean = if Raw = null then null
				            else Text.Replace(
				                    Text.Replace(Raw, "nm", ""),
				                    ",",
				                    ""
				                 ),
				    Parts = if Clean = null then {}
				            else List.Transform(Text.Split(Clean, "-"), each Text.Trim(_)),
				    Numbers =
				        List.RemoveNulls(
				            List.Transform(
				                Parts,
				                each
				                    try Number.FromText(_, "en-US")
				                    otherwise null
				            )
				        )
				in
				    if List.Count(Numbers) = 0
				    then null
				    else List.Min(Numbers)),
				    #"Added Custom8" = Table.AddColumn(#"Added Custom7", "Torque_Max_Nm", each let
				    Raw = if [Torque_Raw] = null then null else Text.Lower(Text.Trim([Torque_Raw])),
				    Clean = if Raw = null then null
				            else Text.Replace(
				                    Text.Replace(Raw, "nm", ""),
				                    ",",
				                    ""
				                 ),
				    Parts = if Clean = null then {}
				            else List.Transform(Text.Split(Clean, "-"), each Text.Trim(_)),
				    Numbers =
				        List.RemoveNulls(
				            List.Transform(
				                Parts,
				                each
				                    try Number.FromText(_, "en-US")
				                    otherwise null
				            )
				        )
				in
				    if List.Count(Numbers) = 0
				    then null
				    else List.Max(Numbers)),
				    #"Added Custom9" = Table.AddColumn(#"Added Custom8", "Torque_Avg_Nm", each let
				    Raw = if [Torque_Raw] = null then null else Text.Lower(Text.Trim([Torque_Raw])),
				    Clean = if Raw = null then null
				            else Text.Replace(
				                    Text.Replace(Raw, "nm", ""),
				                    ",",
				                    ""
				                 ),
				    Parts = if Clean = null then {}
				            else List.Transform(Text.Split(Clean, "-"), each Text.Trim(_)),
				    Numbers =
				        List.RemoveNulls(
				            List.Transform(
				                Parts,
				                each
				                    try Number.FromText(_, "en-US")
				                    otherwise null
				            )
				        )
				in
				    if List.Count(Numbers) = 0
				    then null
				    else List.Average(Numbers)),
				    #"Changed Type6" = Table.TransformColumnTypes(#"Added Custom9",{{"Torque_Avg_Nm", type number}, {"Torque_Max_Nm", type number}, {"Torque_Min_Nm", type number}, {"Price_Avg_USD", type number}, {"Acceleration_0_100_Sec", type number}}),
				    #"Added Custom10" = Table.AddColumn(#"Changed Type6", "Seats_Count", each let
				    Raw =
				        if [Seats_Raw] = null
				        then null
				        else Text.Lower(Text.Trim([Seats_Raw])),
				
				    Parts =
				        if Raw = null
				        then {}
				        else Text.Split(Raw, "+"),
				
				    Numbers =
				        List.RemoveNulls(
				            List.Transform(
				                Parts,
				                each
				                    try Number.FromText(
				                        Text.Trim(_),
				                        "en-US"
				                    )
				                    otherwise null
				            )
				        )
				in
				    if List.Count(Numbers) = 0
				    then null
				    else List.Sum(Numbers)),
				    #"Changed Type7" = Table.TransformColumnTypes(#"Added Custom10",{{"Seats_Count", Int64.Type}}),
				    #"Added Custom11" = Table.AddColumn(#"Changed Type7", "Seats_Layout", each if [Seats_Raw] <> null 
				    and Text.Contains([Seats_Raw], "+")
				then Text.Trim([Seats_Raw])
				else null),
				    #"Added Custom12" = Table.AddColumn(#"Added Custom11", "Fuel_Group", each let
				    Fuel =
				        if [Fuel_Raw] = null 
				        then ""
				        else Text.Lower(Text.Trim([Fuel_Raw]))
				in 
				    if Fuel = "petrol" then "Petrol"
				    else if Fuel = "diesel" then "Diesel"
				    else if Fuel = "electric" then "Electric"
				    else if Fuel = "hybrid" then "Hybrid"
				    else if Text.Contains(Fuel, "plug")
				    and Text.Contains(Fuel,"hybrid") then "Plug-in Hybrid"
				    else if Text.Contains(Fuel, "petrol") and (Text.Contains(Fuel, "hybrid") or Text.Contains(Fuel, "diesel") or Text.Contains(Fuel, "ev")) then "Multi-Fuel"
				    else "Other"),
				    #"Added Custom13" = Table.AddColumn(#"Added Custom12", "Engine_Displacement_CC", each let
				    Raw =
				        if [CC_Battery_Raw] = null
				        then ""
				        else Text.Lower(Text.Trim([CC_Battery_Raw])),
				
				    Parts =
				        List.Transform(
				            Text.Split(Raw, "/"),
				            each Text.Trim(_)
				        ),
				
				    CCParts =
				        List.Select(
				            Parts,
				            each Text.Contains(_, "cc")
				        ),
				
				    FirstCC =
				        if List.Count(CCParts) > 0
				        then CCParts{0}
				        else null,
				
				    NumberText =
				        if FirstCC = null
				        then null
				        else Text.BeforeDelimiter(
				            FirstCC,
				            "cc"
				        ),
				
				    CleanNumber =
				        if NumberText = null
				        then null
				        else Text.Replace(
				            Text.Replace(
				                Text.Trim(NumberText),
				                ",",
				                ""
				            ),
				            " ",
				            ""
				        )
				in
				    try Number.FromText(
				        CleanNumber,
				        "en-US"
				    )
				    otherwise null),
				    #"Added Custom14" = Table.AddColumn(#"Added Custom13", "Battery_Capacity_KWh", each let
				    Raw =
				        if [CC_Battery_Raw] = null
				        then ""
				        else Text.Lower(Text.Trim([CC_Battery_Raw])),
				
				    Parts =
				        List.Transform(
				            Text.Split(Raw, "/"),
				            each Text.Trim(_)
				        ),
				
				    KWhParts =
				        List.Select(
				            Parts,
				            each Text.Contains(_, "kwh")
				        ),
				
				    FirstKWh =
				        if List.Count(KWhParts) > 0
				        then KWhParts{0}
				        else null,
				
				    NumberText =
				        if FirstKWh = null
				        then null
				        else Text.BeforeDelimiter(
				            FirstKWh,
				            "kwh"
				        ),
				
				    CleanNumber =
				        if NumberText = null
				        then null
				        else Text.Replace(
				            Text.Trim(NumberText),
				            " ",
				            ""
				        )
				in
				    try Number.FromText(
				        CleanNumber,
				        "en-US"
				    )
				    otherwise null),
				    #"Added Custom15" = Table.AddColumn(#"Added Custom14", "DataQuality_Flag", each let
				    Issues =
				        List.RemoveNulls({
				            if [Company] = null or Text.Trim([Company]) = ""
				                then "COMPANY"
				                else null,
				
				            if [Car_Name] = null or Text.Trim([Car_Name]) = ""
				                then "CAR_NAME"
				                else null,
				
				            if [Price_Avg_USD] = null
				                then "PRICE"
				                else null,
				
				            if [HorsePower_Avg] = null
				                then "HP"
				                else null,
				
				            if [Speed_KMH] = null
				                then "SPEED"
				                else null,
				
				            if [Acceleration_0_100_Sec] = null
				                then "ACCELERATION"
				                else null,
				
				            if [Torque_Avg_Nm] = null
				                then "TORQUE"
				                else null,
				
				            if [Seats_Count] = null
				                then "SEATS"
				                else null,
				
				            if [Fuel_Group] = "Other"
				                then "FUEL_REVIEW"
				                else null
				        })
				in
				    if List.Count(Issues) = 0
				    then "OK"
				    else Text.Combine(
				        Issues,
				        "; "
				    )),
				    #"Added Custom16" = Table.AddColumn(#"Added Custom15", "Quality_Issue_Count", each let
				    Issues =
				        List.RemoveNulls({
				            if [Company] = null or Text.Trim([Company]) = ""
				                then 1 else null,
				
				            if [Car_Name] = null or Text.Trim([Car_Name]) = ""
				                then 1 else null,
				
				            if [Price_Avg_USD] = null
				                then 1 else null,
				
				            if [HorsePower_Avg] = null
				                then 1 else null,
				
				            if [Speed_KMH] = null
				                then 1 else null,
				
				            if [Acceleration_0_100_Sec] = null
				                then 1 else null,
				
				            if [Torque_Avg_Nm] = null
				                then 1 else null,
				
				            if [Seats_Count] = null
				                then 1 else null,
				
				            if [Fuel_Group] = "Other"
				                then 1 else null
				        })
				in
				    List.Count(Issues)),
				    #"Added Custom17" = Table.AddColumn(#"Added Custom16", "Vehicle_ID", each Text.Combine(
				    {
				        Text.Trim([Company]),
				        Text.Trim([Car_Name]),
				        Text.Trim([Engine_Raw])
				    },
				    "|"
				)),
				    #"Added Custom18" = Table.AddColumn(#"Added Custom17", "HorsePower_Min", each let
				    Raw =
				        if [HorsePower_Raw] = null
				        then null
				        else Text.Lower(Text.Trim([HorsePower_Raw])),
				
				    Clean =
				        if Raw = null
				        then null
				        else Text.Replace(
				            Text.Replace(Raw, "hp", ""),
				            ",",
				            ""
				        ),
				
				    Parts =
				        if Clean = null
				        then {}
				        else List.Transform(
				            Text.Split(Clean, "-"),
				            each Text.Trim(_)
				        ),
				
				    Numbers =
				        List.RemoveNulls(
				            List.Transform(
				                Parts,
				                each
				                    try Number.FromText(_, "en-US")
				                    otherwise null
				            )
				        )
				in
				    if List.Count(Numbers) = 0
				    then null
				    else List.Min(Numbers)),
				    #"Added Custom19" = Table.AddColumn(#"Added Custom18", "HorsePower_Max", each let
				    Raw =
				        if [HorsePower_Raw] = null
				        then null
				        else Text.Lower(Text.Trim([HorsePower_Raw])),
				
				    Clean =
				        if Raw = null
				        then null
				        else Text.Replace(
				            Text.Replace(Raw, "hp", ""),
				            ",",
				            ""
				        ),
				
				    Parts =
				        if Clean = null
				        then {}
				        else List.Transform(
				            Text.Split(Clean, "-"),
				            each Text.Trim(_)
				        ),
				
				    Numbers =
				        List.RemoveNulls(
				            List.Transform(
				                Parts,
				                each
				                    try Number.FromText(_, "en-US")
				                    otherwise null
				            )
				        )
				in
				    if List.Count(Numbers) = 0
				    then null
				    else List.Max(Numbers)),
				    #"Added Custom20" = Table.AddColumn(#"Added Custom19", "HP_Is_Range", each [HorsePower_Min] <> [HorsePower_Max]),
				    #"Changed Type8" = Table.TransformColumnTypes(#"Added Custom20",{{"HP_Is_Range", type logical}, {"HorsePower_Max", type number}, {"HorsePower_Min", type number}, {"Quality_Issue_Count", Int64.Type}, {"Engine_Displacement_CC", type number}, {"Battery_Capacity_KWh", type number}}),
				    #"Reordered Columns" = Table.ReorderColumns(#"Changed Type8",{"Vehicle_ID", "Company", "Car_Name", "Engine_Raw", "CC_Battery_Raw", "Engine_Displacement_CC", "Battery_Capacity_KWh", "HorsePower_Raw", "Speed_KMH", "Speed_Raw", "Acceleration_Raw", "Price_Raw", "HorsePower_Min", "HorsePower_Max", "HorsePower_Avg", "Acceleration_0_100_Sec", "Price_Min_USD", "Price_Max_USD", "Price_Avg_USD", "Price_Is_Range", "Fuel_Raw", "Fuel_Group", "Seats_Raw", "Seats_Count", "Seats_Layout", "Torque_Raw", "Torque_Min_Nm", "Torque_Max_Nm", "Torque_Avg_Nm", "DataQuality_Flag", "Quality_Issue_Count", "HP_Is_Range"}),
				    #"Removed Columns" = Table.RemoveColumns(#"Reordered Columns",{"HorsePower_Raw", "Speed_Raw"}),
				    #"Reordered Columns1" = Table.ReorderColumns(#"Removed Columns",{"Vehicle_ID", "Company", "Car_Name", "Engine_Raw", "CC_Battery_Raw", "Engine_Displacement_CC", "Battery_Capacity_KWh", "Speed_KMH", "Acceleration_0_100_Sec", "Acceleration_Raw", "Price_Raw", "HorsePower_Min", "HorsePower_Max", "HorsePower_Avg", "Price_Min_USD", "Price_Max_USD", "Price_Avg_USD", "Price_Is_Range", "Fuel_Raw", "Fuel_Group", "Seats_Raw", "Seats_Count", "Seats_Layout", "Torque_Raw", "Torque_Min_Nm", "Torque_Max_Nm", "Torque_Avg_Nm", "DataQuality_Flag", "Quality_Issue_Count", "HP_Is_Range"}),
				    #"Removed Columns1" = Table.RemoveColumns(#"Reordered Columns1",{"Acceleration_Raw", "Price_Raw"}),
				    #"Reordered Columns2" = Table.ReorderColumns(#"Removed Columns1",{"Vehicle_ID", "Company", "Car_Name", "Engine_Raw", "CC_Battery_Raw", "Engine_Displacement_CC", "Battery_Capacity_KWh", "HorsePower_Min", "HorsePower_Max", "HorsePower_Avg", "Speed_KMH", "Acceleration_0_100_Sec", "Price_Min_USD", "Price_Max_USD", "Price_Avg_USD", "Price_Is_Range", "Fuel_Raw", "Fuel_Group", "Seats_Raw", "Seats_Count", "Seats_Layout", "Torque_Raw", "Torque_Min_Nm", "Torque_Max_Nm", "Torque_Avg_Nm", "DataQuality_Flag", "Quality_Issue_Count", "HP_Is_Range"}),
				    #"Removed Columns2" = Table.RemoveColumns(#"Reordered Columns2",{"HP_Is_Range"}),
				    #"Changed Type9" = Table.TransformColumnTypes(#"Removed Columns2",{{"Seats_Layout", type text}, {"DataQuality_Flag", type text}}),
				    #"Renamed Columns1" = Table.RenameColumns(#"Changed Type9",{{"Vehicle_ID", "Vehicle_NaturalKey"}}),
				    #"Added Index" = Table.AddIndexColumn(#"Renamed Columns1", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns2" = Table.RenameColumns(#"Added Index",{{"Index", "Vehicle_ID"}}),
				    #"Uppercased Text" = Table.TransformColumns(#"Renamed Columns2",{{"Company", Text.Upper, type text}}),
				    #"Added Custom21" = Table.AddColumn(#"Uppercased Text", "Engine_Key", each if [Engine_Raw] = null then
				    null
				else
				    Text.Upper(
				        Text.Trim(
				            Text.Clean([Engine_Raw])
				        )
				    ))
				in
				    #"Added Custom21"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

