table qa_Cars_Audit
	lineageTag: eaf5f064-f24f-4f7a-ab98-1edaa42dcfcf

	column Vehicle_NaturalKey
		dataType: string
		lineageTag: fc2546ff-a455-46c8-b0d0-baf12c3d1ac2
		summarizeBy: none
		sourceColumn: Vehicle_NaturalKey

		annotation SummarizationSetBy = Automatic

	column Company
		dataType: string
		lineageTag: b1f7b48f-802e-4064-b98a-e81b735a40a1
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	column Car_Name
		dataType: string
		lineageTag: 04ecb481-75c7-4cbe-b837-e55130d88177
		summarizeBy: none
		sourceColumn: Car_Name

		annotation SummarizationSetBy = Automatic

	column Engine_Raw
		dataType: string
		lineageTag: a66b5938-0b8b-4248-9878-ddcaa6f0b06b
		summarizeBy: none
		sourceColumn: Engine_Raw

		annotation SummarizationSetBy = Automatic

	column CC_Battery_Raw
		dataType: string
		lineageTag: 2c0ef89c-2bdb-47dd-a856-e4072a9da59b
		summarizeBy: none
		sourceColumn: CC_Battery_Raw

		annotation SummarizationSetBy = Automatic

	column Engine_Displacement_CC
		dataType: double
		lineageTag: 14000600-8a55-4c2b-92e2-96abf7c15835
		summarizeBy: sum
		sourceColumn: Engine_Displacement_CC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Battery_Capacity_KWh
		dataType: double
		lineageTag: fc76b7fe-a241-4d8b-b3ee-f535e51c8076
		summarizeBy: sum
		sourceColumn: Battery_Capacity_KWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HorsePower_Min
		dataType: double
		lineageTag: 0f9c68a9-e75c-4c21-94e1-083318f43b66
		summarizeBy: sum
		sourceColumn: HorsePower_Min

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HorsePower_Max
		dataType: double
		lineageTag: 932ce7cc-39ce-41e7-9eeb-fdeef6cd2c65
		summarizeBy: sum
		sourceColumn: HorsePower_Max

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HorsePower_Avg
		dataType: double
		lineageTag: 7e2645a5-cdd8-4f44-83b1-ca57ec8700df
		summarizeBy: sum
		sourceColumn: HorsePower_Avg

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Speed_KMH
		dataType: double
		lineageTag: a6755b3b-74fb-4300-80e8-b67e3ee31f5a
		summarizeBy: sum
		sourceColumn: Speed_KMH

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Acceleration_0_100_Sec
		dataType: double
		lineageTag: 5f0e3af3-2f7a-49da-99b7-fb3fd5a392f0
		summarizeBy: sum
		sourceColumn: Acceleration_0_100_Sec

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Price_Min_USD
		dataType: double
		lineageTag: d38015df-12f7-4289-9f29-7fe9e8eef106
		summarizeBy: sum
		sourceColumn: Price_Min_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Price_Max_USD
		dataType: double
		lineageTag: 08f86996-a293-4c3a-8875-04672fb2663b
		summarizeBy: sum
		sourceColumn: Price_Max_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Price_Avg_USD
		dataType: double
		lineageTag: ce3a046c-0fbc-4b82-95d8-9b39ee5a850a
		summarizeBy: sum
		sourceColumn: Price_Avg_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Price_Is_Range
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: e21cb3a7-e14b-4a13-a9af-bfe3fb7e953c
		summarizeBy: none
		sourceColumn: Price_Is_Range

		annotation SummarizationSetBy = Automatic

	column Fuel_Raw
		dataType: string
		lineageTag: adaa91bd-af69-4376-aa01-4ef090af04d7
		summarizeBy: none
		sourceColumn: Fuel_Raw

		annotation SummarizationSetBy = Automatic

	column Fuel_Group
		dataType: string
		lineageTag: 16ef8532-a758-4f5e-9d42-4294f7eb3603
		summarizeBy: none
		sourceColumn: Fuel_Group

		annotation SummarizationSetBy = Automatic

	column Seats_Raw
		dataType: string
		lineageTag: 4b35acd8-15be-4994-86bd-d96f5afb5b09
		summarizeBy: none
		sourceColumn: Seats_Raw

		annotation SummarizationSetBy = Automatic

	column Seats_Count
		dataType: int64
		formatString: 0
		lineageTag: 94bd1fc8-3913-4e71-81b8-a40a98ecabe2
		summarizeBy: sum
		sourceColumn: Seats_Count

		annotation SummarizationSetBy = Automatic

	column Seats_Layout
		dataType: string
		lineageTag: 3192c34a-fb83-49d8-aad1-b15c1cdce749
		summarizeBy: none
		sourceColumn: Seats_Layout

		annotation SummarizationSetBy = Automatic

	column Torque_Raw
		dataType: string
		lineageTag: 97159822-79fe-4c33-90a2-b04963de645d
		summarizeBy: none
		sourceColumn: Torque_Raw

		annotation SummarizationSetBy = Automatic

	column Torque_Min_Nm
		dataType: double
		lineageTag: 56ef8380-643d-4bb2-9472-ed4ef6a83e89
		summarizeBy: sum
		sourceColumn: Torque_Min_Nm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Torque_Max_Nm
		dataType: double
		lineageTag: 9bea35da-0358-4fc6-aaa2-6778a8b4cb60
		summarizeBy: sum
		sourceColumn: Torque_Max_Nm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Torque_Avg_Nm
		dataType: double
		lineageTag: f0ce9dad-df07-445a-bc1b-e9015ed8f66e
		summarizeBy: sum
		sourceColumn: Torque_Avg_Nm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DataQuality_Flag
		dataType: string
		lineageTag: ff37ba7e-845a-44b9-88a1-4d338915b40b
		summarizeBy: none
		sourceColumn: DataQuality_Flag

		annotation SummarizationSetBy = Automatic

	column Quality_Issue_Count
		dataType: int64
		formatString: 0
		lineageTag: 4a95734f-2119-4a64-8598-29d826c079e2
		summarizeBy: sum
		sourceColumn: Quality_Issue_Count

		annotation SummarizationSetBy = Automatic

	column Vehicle_ID
		dataType: int64
		formatString: 0
		lineageTag: d3744392-e383-4907-a250-cda68b759b43
		summarizeBy: none
		sourceColumn: Vehicle_ID

		annotation SummarizationSetBy = Automatic

	partition qa_Cars_Audit = m
		mode: import
		queryGroup: Qa
		source =
				let
				    Source = stg_Cars_Raw,
				    #"Removed Columns" = Table.RemoveColumns(Source,{"Engine_Key"})
				in
				    #"Removed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

