table qa_DuplicateDetails
	lineageTag: 2066e395-7b0b-424e-88a6-948e3a74ea3f

	column Vehicle_NaturalKey
		dataType: string
		lineageTag: 1d0e3a2c-9b0d-40cf-8755-4e5cb9ade048
		summarizeBy: none
		sourceColumn: Vehicle_NaturalKey

		annotation SummarizationSetBy = Automatic

	column Company
		dataType: string
		lineageTag: c7363242-ae55-4d25-b6d4-2a4ecb4bbe26
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	column Car_Name
		dataType: string
		lineageTag: 8b526544-6ffe-4c4a-a78d-1f6da5b672f7
		summarizeBy: none
		sourceColumn: Car_Name

		annotation SummarizationSetBy = Automatic

	column Engine_Raw
		dataType: string
		lineageTag: 005f1350-da15-44fc-91c6-2ab774a50baa
		summarizeBy: none
		sourceColumn: Engine_Raw

		annotation SummarizationSetBy = Automatic

	column CC_Battery_Raw
		dataType: string
		lineageTag: 3972d8fc-1ec2-445c-8b3b-9f66a0b70c3b
		summarizeBy: none
		sourceColumn: CC_Battery_Raw

		annotation SummarizationSetBy = Automatic

	column Engine_Displacement_CC
		dataType: double
		lineageTag: 6502e89c-913b-4437-90ef-b8a7ccedca51
		summarizeBy: sum
		sourceColumn: Engine_Displacement_CC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Battery_Capacity_KWh
		dataType: double
		lineageTag: 3812a8fa-e0d5-4eaf-9da1-ce51400692b0
		summarizeBy: sum
		sourceColumn: Battery_Capacity_KWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HorsePower_Min
		dataType: double
		lineageTag: fecb1b92-12c1-42d7-80ec-ebc87af25a46
		summarizeBy: sum
		sourceColumn: HorsePower_Min

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HorsePower_Max
		dataType: double
		lineageTag: 226af17b-8b9b-4d28-ab8a-421595ec59b9
		summarizeBy: sum
		sourceColumn: HorsePower_Max

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HorsePower_Avg
		dataType: double
		lineageTag: 7c951835-1a85-45bc-a9ac-02b7d47f3ccb
		summarizeBy: sum
		sourceColumn: HorsePower_Avg

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Speed_KMH
		dataType: double
		lineageTag: 46d7510c-acf7-4f9f-a0b0-e485d68875e4
		summarizeBy: sum
		sourceColumn: Speed_KMH

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Acceleration_0_100_Sec
		dataType: double
		lineageTag: 95c9acef-d3b1-4882-83f1-2a68a79d0342
		summarizeBy: sum
		sourceColumn: Acceleration_0_100_Sec

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Price_Min_USD
		dataType: double
		lineageTag: ae1699e5-78ed-469e-b612-5d9df420339a
		summarizeBy: sum
		sourceColumn: Price_Min_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Price_Max_USD
		dataType: double
		lineageTag: 8510221e-3c45-4b63-be21-0c801d584fcf
		summarizeBy: sum
		sourceColumn: Price_Max_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Price_Avg_USD
		dataType: double
		lineageTag: c587c6df-0886-4773-a456-9fa43c3c7d9c
		summarizeBy: sum
		sourceColumn: Price_Avg_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Price_Is_Range
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 5a6d1c29-a0cc-4f48-9ecb-43401b6a33cb
		summarizeBy: none
		sourceColumn: Price_Is_Range

		annotation SummarizationSetBy = Automatic

	column Fuel_Raw
		dataType: string
		lineageTag: a5017475-3d23-46cf-9312-349c295170a5
		summarizeBy: none
		sourceColumn: Fuel_Raw

		annotation SummarizationSetBy = Automatic

	column Fuel_Group
		dataType: string
		lineageTag: 904490d1-cf04-491b-a6c2-7a447ef0fbf8
		summarizeBy: none
		sourceColumn: Fuel_Group

		annotation SummarizationSetBy = Automatic

	column Seats_Raw
		dataType: string
		lineageTag: 3fcc735c-8b08-415b-9e0b-47c358075a36
		summarizeBy: none
		sourceColumn: Seats_Raw

		annotation SummarizationSetBy = Automatic

	column Seats_Count
		dataType: int64
		formatString: 0
		lineageTag: ed0e7327-be62-45f6-a1ba-90573989d355
		summarizeBy: sum
		sourceColumn: Seats_Count

		annotation SummarizationSetBy = Automatic

	column Seats_Layout
		dataType: string
		lineageTag: 2411f542-ecea-4b77-b963-9e9f600dd528
		summarizeBy: none
		sourceColumn: Seats_Layout

		annotation SummarizationSetBy = Automatic

	column Torque_Raw
		dataType: string
		lineageTag: e44d0bcd-220c-46c1-8b60-687236fd70e6
		summarizeBy: none
		sourceColumn: Torque_Raw

		annotation SummarizationSetBy = Automatic

	column Torque_Min_Nm
		dataType: double
		lineageTag: 900c66d6-c5bd-44a8-9ffb-0d2a54cb2da9
		summarizeBy: sum
		sourceColumn: Torque_Min_Nm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Torque_Max_Nm
		dataType: double
		lineageTag: 0cca1c8a-5c0b-4eba-ae2b-5607a607fd2e
		summarizeBy: sum
		sourceColumn: Torque_Max_Nm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Torque_Avg_Nm
		dataType: double
		lineageTag: 443b5d02-5bf4-4658-942c-d6aa28761579
		summarizeBy: sum
		sourceColumn: Torque_Avg_Nm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DataQuality_Flag
		dataType: string
		lineageTag: ec090dbf-b8ea-4780-b05f-2bcfa800a150
		summarizeBy: none
		sourceColumn: DataQuality_Flag

		annotation SummarizationSetBy = Automatic

	column Quality_Issue_Count
		dataType: int64
		formatString: 0
		lineageTag: fe37e98b-f8fe-40a6-b6fb-dcf62493420f
		summarizeBy: sum
		sourceColumn: Quality_Issue_Count

		annotation SummarizationSetBy = Automatic

	column Vehicle_ID
		dataType: int64
		formatString: 0
		lineageTag: fea2e241-1fae-4451-8758-a5afa93d2edd
		summarizeBy: none
		sourceColumn: Vehicle_ID

		annotation SummarizationSetBy = Automatic

	column Engine_Key
		dataType: string
		lineageTag: bc2d44d6-d208-408b-a9f9-85b603878a57
		summarizeBy: none
		sourceColumn: Engine_Key

		annotation SummarizationSetBy = Automatic

	partition qa_DuplicateDetails = m
		mode: import
		queryGroup: Qa
		source =
				let
				    Source = stg_Cars_Raw,
				    #"Merged Queries" = Table.NestedJoin(Source, {"Vehicle_NaturalKey"}, qa_DuplicateVehicles, {"Vehicle_NaturalKey"}, "qa_DuplicateVehicles", JoinKind.LeftOuter)
				in
				    #"Merged Queries"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

