table qa_DuplicateVehicles
	lineageTag: 95d993b4-0b2a-4b5a-8707-16df3fb728ce

	column Vehicle_NaturalKey
		dataType: string
		lineageTag: 4e700b1a-c96d-482e-9f7d-27b965ddafa8
		summarizeBy: none
		sourceColumn: Vehicle_NaturalKey

		annotation SummarizationSetBy = Automatic

	column Row_Count
		dataType: int64
		formatString: 0
		lineageTag: 7daf2a87-f891-40c5-a2a2-5d1d447377bc
		summarizeBy: sum
		sourceColumn: Row_Count

		annotation SummarizationSetBy = Automatic

	partition qa_DuplicateVehicles = m
		mode: import
		queryGroup: Qa
		source =
				let
				    Source = stg_Cars_Raw,
				    #"Selected Columns" = Table.SelectColumns(Source, {"Vehicle_NaturalKey"}),
				    #"Grouped Rows" = Table.Group(#"Selected Columns", {"Vehicle_NaturalKey"}, {{"Row_Count", each Table.RowCount(_), Int64.Type}}),
				    #"Filtered Rows" = Table.SelectRows(#"Grouped Rows", each [Row_Count] > 1)
				in
				    #"Filtered Rows"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

