table stg_Cars_Raw
	lineageTag: 350e3cc5-bb52-4d6f-9b7d-e50b56212372

	column Company
		dataType: string
		lineageTag: 1d50bead-1862-40b4-b4c3-be3064e3e2ac
		summarizeBy: none
		sourceColumn: Company

		annotation SummarizationSetBy = Automatic

	column Car_Name
		dataType: string
		lineageTag: 43738042-131d-4bc2-b934-35ad7a52e7f4
		summarizeBy: none
		sourceColumn: Car_Name

		annotation SummarizationSetBy = Automatic

	column Engine_Raw
		dataType: string
		lineageTag: 0950f5e0-cbff-4116-8b35-ffd7769ae11c
		summarizeBy: none
		sourceColumn: Engine_Raw

		annotation SummarizationSetBy = Automatic

	column CC_Battery_Raw
		dataType: string
		lineageTag: 885661e7-bf8b-4024-86d6-d269b7d9398f
		summarizeBy: none
		sourceColumn: CC_Battery_Raw

		annotation SummarizationSetBy = Automatic

	column HorsePower_Raw
		dataType: string
		lineageTag: 787213c8-78b7-4437-a5a4-e106c4c94c2b
		summarizeBy: none
		sourceColumn: HorsePower_Raw

		annotation SummarizationSetBy = Automatic

	column Speed_Raw
		dataType: string
		lineageTag: 97d7c6e7-6e91-4500-9a80-589dad2afbfd
		summarizeBy: none
		sourceColumn: Speed_Raw

		annotation SummarizationSetBy = Automatic

	column Acceleration_Raw
		dataType: string
		lineageTag: f7560c28-704e-4aca-83a1-152544ff9623
		summarizeBy: none
		sourceColumn: Acceleration_Raw

		annotation SummarizationSetBy = Automatic

	column Price_Raw
		dataType: string
		lineageTag: c469ee40-da00-424d-9550-005988067a67
		summarizeBy: none
		sourceColumn: Price_Raw

		annotation SummarizationSetBy = Automatic

	column Fuel_Raw
		dataType: string
		lineageTag: 6d8aa7dd-a0ea-4c38-aa5a-bd03801d820b
		summarizeBy: none
		sourceColumn: Fuel_Raw

		annotation SummarizationSetBy = Automatic

	column Seats_Raw
		dataType: string
		lineageTag: a382d203-30cf-48d8-9c3b-2bc517c77da6
		summarizeBy: none
		sourceColumn: Seats_Raw

		annotation SummarizationSetBy = Automatic

	column Torque_Raw
		dataType: string
		lineageTag: 3da64576-7b4f-4e79-89f4-ca134c6ebbf8
		summarizeBy: none
		sourceColumn: Torque_Raw

		annotation SummarizationSetBy = Automatic

	column HorsePower_Avg
		dataType: double
		lineageTag: 833dd19d-53c0-45b2-961e-77d4ec4d203c
		summarizeBy: sum
		sourceColumn: HorsePower_Avg

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Speed_KMH
		dataType: double
		lineageTag: 5315f50a-1820-4888-99c2-564fa735472e
		summarizeBy: sum
		sourceColumn: Speed_KMH

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Acceleration_0_100_Sec
		dataType: double
		lineageTag: d6999a8b-b04e-4d75-b457-e6453d9e8e7f
		summarizeBy: sum
		sourceColumn: Acceleration_0_100_Sec

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Price_Min_USD
		dataType: double
		lineageTag: 51402b8f-61cd-4b09-87fa-39c3bed4b4a1
		summarizeBy: sum
		sourceColumn: Price_Min_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Price_Max_USD
		dataType: double
		lineageTag: ba173e29-f0d2-4c24-bf5a-8a8933c782e4
		summarizeBy: sum
		sourceColumn: Price_Max_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Price_Avg_USD
		dataType: double
		lineageTag: 45059026-2538-47aa-b55f-4c2d3502de29
		summarizeBy: sum
		sourceColumn: Price_Avg_USD

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Price_Is_Range
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 97f095d5-07a7-43b9-9d6c-0e46c107a9bc
		summarizeBy: none
		sourceColumn: Price_Is_Range

		annotation SummarizationSetBy = Automatic

	column Torque_Min_Nm
		dataType: double
		lineageTag: 5bb37fdd-7a6e-424b-b2bc-873d8ab0f434
		summarizeBy: sum
		sourceColumn: Torque_Min_Nm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Torque_Max_Nm
		dataType: double
		lineageTag: e8c68af7-854d-42da-8c47-c386c61f00f1
		summarizeBy: sum
		sourceColumn: Torque_Max_Nm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Torque_Avg_Nm
		dataType: double
		lineageTag: f4280475-1c50-4074-84b4-ddf92d60158d
		summarizeBy: sum
		sourceColumn: Torque_Avg_Nm

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Seats_Count
		dataType: int64
		formatString: 0
		lineageTag: 5a95d791-88de-4c51-bc02-982d733dd940
		summarizeBy: sum
		sourceColumn: Seats_Count

		annotation SummarizationSetBy = Automatic

	column Seats_Layout
		dataType: string
		lineageTag: cae5eb39-a644-4315-8e6e-285445ffcb11
		summarizeBy: none
		sourceColumn: Seats_Layout

		annotation SummarizationSetBy = Automatic

	column Fuel_Group
		dataType: string
		lineageTag: d3087db9-ed2e-417d-9a96-30d2d92f7133
		summarizeBy: none
		sourceColumn: Fuel_Group

		annotation SummarizationSetBy = Automatic

	column Engine_Displacement_CC
		dataType: double
		lineageTag: ff9e3350-21d9-4e50-9132-134e83dd1fef
		summarizeBy: sum
		sourceColumn: Engine_Displacement_CC

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Battery_Capacity_KWh
		dataType: double
		lineageTag: 22849abe-a637-4c24-a9f5-a2d7f36f7667
		summarizeBy: sum
		sourceColumn: Battery_Capacity_KWh

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column DataQuality_Flag
		dataType: string
		lineageTag: 84360232-ce8e-4f82-bcae-e86748c4d38a
		summarizeBy: none
		sourceColumn: DataQuality_Flag

		annotation SummarizationSetBy = Automatic

	column Quality_Issue_Count
		dataType: int64
		formatString: 0
		lineageTag: 1b871c02-003d-48be-bf6e-45e256656ba6
		summarizeBy: sum
		sourceColumn: Quality_Issue_Count

		annotation SummarizationSetBy = Automatic

	column Vehicle_NaturalKey
		dataType: string
		lineageTag: 0f6a119c-e0a7-4b00-9e12-a8ba6dc3015d
		summarizeBy: none
		sourceColumn: Vehicle_NaturalKey

		annotation SummarizationSetBy = Automatic

	column HorsePower_Min
		dataType: double
		lineageTag: 3aeb8e7a-8735-41a2-84de-cfd1ed3a5988
		summarizeBy: sum
		sourceColumn: HorsePower_Min

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HorsePower_Max
		dataType: double
		lineageTag: 7daa62a3-de8a-47dc-9ccf-abf5933773ad
		summarizeBy: sum
		sourceColumn: HorsePower_Max

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column HP_Is_Range
		dataType: boolean
		formatString: """TRUE"";""TRUE"";""FALSE"""
		lineageTag: 0deb7ada-ac5d-481f-b470-99f006dc501e
		summarizeBy: none
		sourceColumn: HP_Is_Range

		annotation SummarizationSetBy = Automatic

	column Vehicle_ID
		dataType: int64
		formatString: 0
		lineageTag: 3aa9a8e8-543f-44d2-988b-124b9fa10bd7
		summarizeBy: count
		sourceColumn: Vehicle_ID

		annotation SummarizationSetBy = Automatic

	partition stg_Cars_Raw = m
		mode: import
		queryGroup: 'Main Querys'
		source = ```
				let
				  Source = Csv.Document(File.Contents("C:\Users\Juanma\Desktop\cars-intelligence-2025\data\raw\Cars Datasets 2025.csv"), [Delimiter = ",", Columns = 11, QuoteStyle = QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Company Names", type text}, {"Cars Names", type text}, {"Engines", type text}, {"CC/Battery Capacity", type text}, {"HorsePower", type text}, {"Total Speed", type text}, {"Performance(0 - 100 )KM/H", type text}, {"Cars Prices", type text}, {"Fuel Types", type text}, {"Seats", type text}, {"Torque", type text}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Company Names", "Company"}, {"Cars Names", "Car_Name"}, {"Engines", "Engine_Raw"}, {"CC/Battery Capacity", "CC_Battery_Raw"}, {"HorsePower", "HorsePower_Raw"}, {"Total Speed", "Speed_Raw"}, {"Performance(0 - 100 )KM/H", "Acceleration_Raw"}, {"Cars Prices", "Price_Raw"}, {"Fuel Types", "Fuel_Raw"}, {"Seats", "Seats_Raw"}, {"Torque", "Torque_Raw"}}),
				    #"Trimmed Text" = Table.TransformColumns(#"Renamed Columns",{{"Company", Text.Trim, type text}, {"Car_Name", Text.Trim, type text}, {"Engine_Raw", Text.Trim, type text}, {"CC_Battery_Raw", Text.Trim, type text}, {"HorsePower_Raw", Text.Trim, type text}, {"Speed_Raw", Text.Trim, type text}, {"Acceleration_Raw", Text.Trim, type text}, {"Price_Raw", Text.Trim, type text}, {"Fuel_Raw", Text.Trim, type text}, {"Seats_Raw", Text.Trim, type text}, {"Torque_Raw", Text.Trim, type text}}),
				    #"Cleaned Text" = Table.TransformColumns(#"Trimmed Text",{{"Company", Text.Clean, type text}, {"Car_Name", Text.Clean, type text}, {"Engine_Raw", Text.Clean, type text}, {"CC_Battery_Raw", Text.Clean, type text}, {"HorsePower_Raw", Text.Clean, type text}, {"Speed_Raw", Text.Clean, type text}, {"Acceleration_Raw", Text.Clean, type text}, {"Price_Raw", Text.Clean, type text}, {"Fuel_Raw", Text.Clean, type text}, {"Seats_Raw", Text.Clean, type text}, {"Torque_Raw", Text.Clean, type text}}),
				    #"Added Custom" = Table.AddColumn(#"Cleaned Text", "HorsePower_Avg", each fx_ParseRangeNumber([HorsePower_Raw])),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Added Custom",{{"HorsePower_Avg", type number}}),
				    #"Added Custom1" = Table.AddColumn(#"Changed Type1", "Speed_KMH", each try Number.FromText(
				    Text.BeforeDelimiter(
				        Text.Lower([Speed_Raw]),
				        "km/h"
				    )
				) otherwise null),
				    #"Changed Type2" = Table.TransformColumnTypes(#"Added Custom1",{{"Speed_KMH", type number}}),
				    #"Added Custom2" = Table.AddColumn(#"Changed Type2", "Acceleration_0_100_Sec", each try Number.FromText(
				    Text.Trim(
				        Text.Replace(
				            Text.BeforeDelimiter(
				                Text.Lower([Acceleration_Raw]),
				                "sec"
				            ),
				            " ",
				            ""
				         )
				    )
				) otherwise null),
				    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "Price_Min_USD", each let
				    Raw = if [Price_Raw] = null then null else Text.Trim([Price_Raw]),
				    Clean = if Raw = null then null
				            else Text.Replace(
				                    Text.Replace(Raw, "$", ""),
				                    ",",
				                    ""
				                 ),
				    Parts = if Clean = null then {}
				            else List.Transform(
				                    Text.Split(Clean, "-"),
				                    each Text.Trim(_)
				                 ),
				    Numbers =
				        List.RemoveNulls(
				            List.Transform(
				                Parts,
				                each
				                    try Number.FromText(_, "en-US")
				                    otherwise null
				            )
				        )
				in
				    if List.Count(Numbers) = 0
				    then null
				    else List.Min(Numbers)),
				    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom3",{{"Price_Min_USD", type number}}),
				    #"Added Custom4" = Table.AddColumn(#"Changed Type3", "Price_Max_USD", each let
				    Raw = if [Price_Raw] = null then null else Text.Trim([Price_Raw]),
				    Clean = if Raw = null then null
				            else Text.Replace(
				                    Text.Replace(Raw, "$", ""),
				                    ",",
				                    ""
				                 ),
				    Parts = if Clean = null then {}
				            else List.Transform(
				                    Text.Split(Clean, "-"),
				                    each Text.Trim(_)
				                 ),
				    Numbers =
				        List.RemoveNulls(
				            List.Transform(
				                Parts,
				                each
				                    try Number.FromText(_, "en-US")
				                    otherwise null
				            )
				        )
				in
				    if List.Count(Numbers) = 0
				    then null
				    else List.Max(Numbers)),
				    #"Changed Type4" = Table.TransformColumnTypes(#"Added Custom4",{{"Price_Max_USD", type number}}),
				    #"Added Custom5" = Table.AddColumn(#"Changed Type4", "Price_Avg_USD", each let
				    Raw = if [Price_Raw] = null then null else Text.Trim([Price_Raw]),
				    Clean = if Raw = null then null
				            else Text.Replace(
				                    Text.Replace(Raw, "$", ""),
				                    ",",
				                    ""
				                 ),
				    Parts = if Clean = null then {}
				            else List.Transform(
				                    Text.Split(Clean, "-"),
				                    each Text.Trim(_)
				                 ),
				    Numbers =
				        List.RemoveNulls(
				            List.Transform(
				                Parts,
				                each
				                    try Number.FromText(_, "en-US")
				                    otherwise null
				            )
				        )
				in
				    if List.Count(Numbers) = 0
				    then null
				    else List.Average(Numbers)),
				    #"Added Custom6" = Table.AddColumn(#"Added Custom5", "Price_Is_Range", each if [Price_Min_USD] <> [Price_Max_USD]
				then true 
				else false),
				    #"Changed Type5" = Table.TransformColumnTypes(#"Added Custom6",{{"Price_Is_Range", type logical}}),
				    #"Added Custom7" = Table.AddColumn(#"Changed Type5", "Torque_Min_Nm", each let
				    Raw = if [Torque_Raw] = null then null else Text.Lower(Text.Trim([Torque_Raw])),
				    Clean = if Raw = null then null
				            else Text.Replace(
				                    Text.Replace(Raw, "nm", ""),
				                    ",",
				                    ""
				                 ),
				    Parts = if Clean = null then {}
				            else List.Transform(Text.Split(Clean, "-"), each Text.Trim(_)),
				    Numbers =
				        List.RemoveNulls(
				            List.Transform(
				                Parts,
				                each
				                    try Number.FromText(_, "en-US")
				                    otherwise null
				            )
				        )
				in
				    if List.Count(Numbers) = 0
				    then null
				    else List.Min(Numbers)),
				    #"Added Custom8" = Table.AddColumn(#"Added Custom7", "Torque_Max_Nm", each let
				    Raw = if [Torque_Raw] = null then null else Text.Lower(Text.Trim([Torque_Raw])),
				    Clean = if Raw = null then null
				            else Text.Replace(
				                    Text.Replace(Raw, "nm", ""),
				                    ",",
				                    ""
				                 ),
				    Parts = if Clean = null then {}
				            else List.Transform(Text.Split(Clean, "-"), each Text.Trim(_)),
				    Numbers =
				        List.RemoveNulls(
				            List.Transform(
				                Parts,
				                each
				                    try Number.FromText(_, "en-US")
				                    otherwise null
				            )
				        )
				in
				    if List.Count(Numbers) = 0
				    then null
				    else List.Max(Numbers)),
				    #"Added Custom9" = Table.AddColumn(#"Added Custom8", "Torque_Avg_Nm", each let
				    Raw = if [Torque_Raw] = null then null else Text.Lower(Text.Trim([Torque_Raw])),
				    Clean = if Raw = null then null
				            else Text.Replace(
				                    Text.Replace(Raw, "nm", ""),
				                    ",",
				                    ""
				                 ),
				    Parts = if Clean = null then {}
				            else List.Transform(Text.Split(Clean, "-"), each Text.Trim(_)),
				    Numbers =
				        List.RemoveNulls(
				            List.Transform(
				                Parts,
				                each
				                    try Number.FromText(_, "en-US")
				                    otherwise null
				            )
				        )
				in
				    if List.Count(Numbers) = 0
				    then null
				    else List.Average(Numbers)),
				    #"Changed Type6" = Table.TransformColumnTypes(#"Added Custom9",{{"Torque_Avg_Nm", type number}, {"Torque_Max_Nm", type number}, {"Torque_Min_Nm", type number}, {"Price_Avg_USD", type number}, {"Acceleration_0_100_Sec", type number}}),
				    #"Added Custom10" = Table.AddColumn(#"Changed Type6", "Seats_Count", each let
				    Raw =
				        if [Seats_Raw] = null
				        then null
				        else Text.Lower(Text.Trim([Seats_Raw])),
				
				    Parts =
				        if Raw = null
				        then {}
				        else Text.Split(Raw, "+"),
				
				    Numbers =
				        List.RemoveNulls(
				            List.Transform(
				                Parts,
				                each
				                    try Number.FromText(
				                        Text.Trim(_),
				                        "en-US"
				                    )
				                    otherwise null
				            )
				        )
				in
				    if List.Count(Numbers) = 0
				    then null
				    else List.Sum(Numbers)),
				    #"Changed Type7" = Table.TransformColumnTypes(#"Added Custom10",{{"Seats_Count", Int64.Type}}),
				    #"Added Custom11" = Table.AddColumn(#"Changed Type7", "Seats_Layout", each if [Seats_Raw] <> null 
				    and Text.Contains([Seats_Raw], "+")
				then Text.Trim([Seats_Raw])
				else null),
				    #"Added Custom12" = Table.AddColumn(#"Added Custom11", "Fuel_Group", each let
				    Fuel =
				        if [Fuel_Raw] = null 
				        then ""
				        else Text.Lower(Text.Trim([Fuel_Raw]))
				in 
				    if Fuel = "petrol" then "Petrol"
				    else if Fuel = "diesel" then "Diesel"
				    else if Fuel = "electric" then "Electric"
				    else if Fuel = "hybrid" then "Hybrid"
				    else if Text.Contains(Fuel, "plug")
				    and Text.Contains(Fuel,"hybrid") then "Plug-in Hybrid"
				    else if Text.Contains(Fuel, "petrol") and (Text.Contains(Fuel, "hybrid") or Text.Contains(Fuel, "diesel") or Text.Contains(Fuel, "ev")) then "Multi-Fuel"
				    else "Other"),
				    #"Added Custom13" = Table.AddColumn(#"Added Custom12", "Engine_Displacement_CC", each let
				    Raw =
				        if [CC_Battery_Raw] = null
				        then ""
				        else Text.Lower(Text.Trim([CC_Battery_Raw])),
				
				    Parts =
				        List.Transform(
				            Text.Split(Raw, "/"),
				            each Text.Trim(_)
				        ),
				
				    CCParts =
				        List.Select(
				            Parts,
				            each Text.Contains(_, "cc")
				        ),
				
				    FirstCC =
				        if List.Count(CCParts) > 0
				        then CCParts{0}
				        else null,
				
				    NumberText =
				        if FirstCC = null
				        then null
				        else Text.BeforeDelimiter(
				            FirstCC,
				            "cc"
				        ),
				
				    CleanNumber =
				        if NumberText = null
				        then null
				        else Text.Replace(
				            Text.Replace(
				                Text.Trim(NumberText),
				                ",",
				                ""
				            ),
				            " ",
				            ""
				        )
				in
				    try Number.FromText(
				        CleanNumber,
				        "en-US"
				    )
				    otherwise null),
				    #"Added Custom14" = Table.AddColumn(#"Added Custom13", "Battery_Capacity_KWh", each let
				    Raw =
				        if [CC_Battery_Raw] = null
				        then ""
				        else Text.Lower(Text.Trim([CC_Battery_Raw])),
				
				    Parts =
				        List.Transform(
				            Text.Split(Raw, "/"),
				            each Text.Trim(_)
				        ),
				
				    KWhParts =
				        List.Select(
				            Parts,
				            each Text.Contains(_, "kwh")
				        ),
				
				    FirstKWh =
				        if List.Count(KWhParts) > 0
				        then KWhParts{0}
				        else null,
				
				    NumberText =
				        if FirstKWh = null
				        then null
				        else Text.BeforeDelimiter(
				            FirstKWh,
				            "kwh"
				        ),
				
				    CleanNumber =
				        if NumberText = null
				        then null
				        else Text.Replace(
				            Text.Trim(NumberText),
				            " ",
				            ""
				        )
				in
				    try Number.FromText(
				        CleanNumber,
				        "en-US"
				    )
				    otherwise null),
				    #"Added Custom15" = Table.AddColumn(#"Added Custom14", "DataQuality_Flag", each let
				    Issues =
				        List.RemoveNulls({
				            if [Company] = null or Text.Trim([Company]) = ""
				                then "COMPANY"
				                else null,
				
				            if [Car_Name] = null or Text.Trim([Car_Name]) = ""
				                then "CAR_NAME"
				                else null,
				
				            if [Price_Avg_USD] = null
				                then "PRICE"
				                else null,
				
				            if [HorsePower_Avg] = null
				                then "HP"
				                else null,
				
				            if [Speed_KMH] = null
				                then "SPEED"
				                else null,
				
				            if [Acceleration_0_100_Sec] = null
				                then "ACCELERATION"
				                else null,
				
				            if [Torque_Avg_Nm] = null
				                then "TORQUE"
				                else null,
				
				            if [Seats_Count] = null
				                then "SEATS"
				                else null,
				
				            if [Fuel_Group] = "Other"
				                then "FUEL_REVIEW"
				                else null
				        })
				in
				    if List.Count(Issues) = 0
				    then "OK"
				    else Text.Combine(
				        Issues,
				        "; "
				    )),
				    #"Added Custom16" = Table.AddColumn(#"Added Custom15", "Quality_Issue_Count", each let
				    Issues =
				        List.RemoveNulls({
				            if [Company] = null or Text.Trim([Company]) = ""
				                then 1 else null,
				
				            if [Car_Name] = null or Text.Trim([Car_Name]) = ""
				                then 1 else null,
				
				            if [Price_Avg_USD] = null
				                then 1 else null,
				
				            if [HorsePower_Avg] = null
				                then 1 else null,
				
				            if [Speed_KMH] = null
				                then 1 else null,
				
				            if [Acceleration_0_100_Sec] = null
				                then 1 else null,
				
				            if [Torque_Avg_Nm] = null
				                then 1 else null,
				
				            if [Seats_Count] = null
				                then 1 else null,
				
				            if [Fuel_Group] = "Other"
				                then 1 else null
				        })
				in
				    List.Count(Issues)),
				    #"Added Custom17" = Table.AddColumn(#"Added Custom16", "Vehicle_ID", each Text.Combine(
				    {
				        Text.Trim([Company]),
				        Text.Trim([Car_Name]),
				        Text.Trim([Engine_Raw])
				    },
				    "|"
				)),
				    #"Added Custom18" = Table.AddColumn(#"Added Custom17", "HorsePower_Min", each let
				    Raw =
				        if [HorsePower_Raw] = null
				        then null
				        else Text.Lower(Text.Trim([HorsePower_Raw])),
				
				    Clean =
				        if Raw = null
				        then null
				        else Text.Replace(
				            Text.Replace(Raw, "hp", ""),
				            ",",
				            ""
				        ),
				
				    Parts =
				        if Clean = null
				        then {}
				        else List.Transform(
				            Text.Split(Clean, "-"),
				            each Text.Trim(_)
				        ),
				
				    Numbers =
				        List.RemoveNulls(
				            List.Transform(
				                Parts,
				                each
				                    try Number.FromText(_, "en-US")
				                    otherwise null
				            )
				        )
				in
				    if List.Count(Numbers) = 0
				    then null
				    else List.Min(Numbers)),
				    #"Added Custom19" = Table.AddColumn(#"Added Custom18", "HorsePower_Max", each let
				    Raw =
				        if [HorsePower_Raw] = null
				        then null
				        else Text.Lower(Text.Trim([HorsePower_Raw])),
				
				    Clean =
				        if Raw = null
				        then null
				        else Text.Replace(
				            Text.Replace(Raw, "hp", ""),
				            ",",
				            ""
				        ),
				
				    Parts =
				        if Clean = null
				        then {}
				        else List.Transform(
				            Text.Split(Clean, "-"),
				            each Text.Trim(_)
				        ),
				
				    Numbers =
				        List.RemoveNulls(
				            List.Transform(
				                Parts,
				                each
				                    try Number.FromText(_, "en-US")
				                    otherwise null
				            )
				        )
				in
				    if List.Count(Numbers) = 0
				    then null
				    else List.Max(Numbers)),
				    #"Added Custom20" = Table.AddColumn(#"Added Custom19", "HP_Is_Range", each [HorsePower_Min] <> [HorsePower_Max]),
				    #"Changed Type8" = Table.TransformColumnTypes(#"Added Custom20",{{"HP_Is_Range", type logical}, {"HorsePower_Max", type number}, {"HorsePower_Min", type number}, {"Quality_Issue_Count", Int64.Type}, {"Engine_Displacement_CC", type number}, {"Battery_Capacity_KWh", type number}}),
				    #"Added Index" = Table.AddIndexColumn(#"Changed Type8", "Index", 1, 1, Int64.Type),
				    #"Renamed Columns1" = Table.RenameColumns(#"Added Index",{{"Vehicle_ID", "Vehicle_NaturalKey"}, {"Index", "Vehicle_ID"}})
				in
				    #"Renamed Columns1"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

